buildInfo:
  github_repo_name: {{github_repo_name}}
  ecr_repo_name: {{ecr_repo_name}}
app:
  image: {{app_image}}
  tag: {{app_image_tag}}
  port: 9090
  monitoringPort: 9096
  livenessProbe: /actuator/health/liveness
  readinessProbe: /actuator/health/readiness
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 300Mi
  limits:
    memory: 420Mi
env:
  plaintext:
    POSTGRES_CONNECT_URL: 'jdbc:postgresql://{{rds_host}}:{{rds_port}}/{{production_quality_db}}?ApplicationName=production-quality'
    POSTGRES_CONNECTION_POOL: {{postgres_connection_pool}}
    POSTGRES_AUTO_DDL: {{postgres_auto_ddl}}
    KAFKA_BROKER_SERVICE_URL: '{% for kafka_ip in kafka_ips %}{{kafka_ip}}:{{kafka_port}}{% if not loop.last %},{% endif %}{% endfor %}'
    EP_PLANT_MASTER_BASE_URL: 'http://plant-master'
    JAVA_TOOL_OPTIONS: '{{default_java_flags}}'
  secret:
    POSTGRES_USERNAME: {{production_quality_db_username}}
    POSTGRES_PASSWORD: {{production_quality_db_password}}
podmonitor:
  endpoints:
    - path: /actuator/prometheus
service:
  port: 80
kong:
  image: {{kong_configure_image}}
  tag: {{kong_configure_image_tag}}
  services:
    - name: production-quality
      authn: oidc-auth
      user_info_endpoint: {{keycloak_user_info_endpoint}}
      response_transformers:
        - "Cache-Control: no-cache"
        - "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
        - "Content-Security-Policy: default-src 'none'"
        - "X-Content-Type-Options: nosniff"
        - "X-XSS-Protection: 1; mode=block"
        - "X-Frame-Options: SAMEORIGIN"
      service_path: /
      routes:
        paths:
          - /production-quality
        strip_path: "true"