buildInfo:
  github_repo_name: {{github_repo_name}}
  ecr_repo_name: {{ecr_repo_name}}
app:
  image: {{app_image}}
  tag: {{app_image_tag}}
  port: 9090
  monitoringPort: 9096
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 470Mi
env:
  plaintext:
    POSTGRES_CONNECT_URL: 'jdbc:postgresql://{{rds_host}}:{{rds_port}}/{{production_planning_db}}?ApplicationName=production-planning-temporary'
    POSTGRES_CONNECTION_POOL: {{postgres_connection_pool}}
    POSTGRES_AUTO_DDL: validate
    FLYWAY_ENABLE: true
    FLYWAY_LOCATIONS: {{flyway_locations}}
    FLYWAY_BASELINE_ON_MIGRATE: {{flyway_baseline_on_migrate}}
    KAFKA_BROKER_SERVICE_URL: '{% for kafka_ip in kafka_ips %}{{kafka_ip}}:{{kafka_port}}{% if not loop.last %},{% endif %}{% endfor %}'
    EP_MATERIAL_MASTER_BASE_URL: 'http://material-master'
    EP_AUTHENTICATION_SCHEME: 'https'
    EP_AUTHENTICATION_HOST: 'auth.ep-dev.tatamotors.com'
    EP_AUTHENTICATION_PORT: '443'
    EP_AUTHENTICATION_REALM: 'enterprise'
    EP_AUTHENTICATION_CLIENT_ID: 'support-dev'
    BUSINESS_UNIT_NAME: 'CVBU'
  secret:
    POSTGRES_USERNAME: {{production_planning_db_username}}
    POSTGRES_PASSWORD: {{production_planning_db_password}}
    EP_AUTHENTICATION_USERNAME: {{production_planning_api_username}}
    EP_AUTHENTICATION_PASSWORD: '{{production_planning_api_password}}'
    EP_AUTHENTICATION_CLIENT_SECRET: {{production_planning_api_client_secret}}
podmonitor:
  endpoints:
    - path: /actuator/prometheus
service:
  port: 80