# Harry's Generated App Config: redis-cache
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: harry-dev
  labels:
    app: redis-cache
    environment: dev
    generated-by: harry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
        environment: dev
    spec:
      containers:
      - name: redis-cache
        image: redis:6.2
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache-service
  namespace: harry-dev
spec:
  selector:
    app: redis-cache
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
