buildInfo:
  github_repo_name: {{github_repo_name}}
  ecr_repo_name: {{ecr_repo_name}}
app:
  image: {{app_image}}
  tag: {{app_image_tag}}
  port: 80
  monitoringPort: 80
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 4Mi
mounts:
  secret:
    - name: ep-app-data
      target: /usr/share/nginx/html/EPAppData.js
      content: |
        window.epAppData = {
          API_BASE_URL: "https://api.{{ep_base_domain}}",
          AUTH_ENDPOINT: "{{central_keycloak_base_url}}/auth",
          UI_BASE_URL: "https://configurator.{{ep_base_domain}}",
          ESAKHA_API_BASE_URL: "https://api.{{esakha_base_domain}}",
        }
    - name: keycloak-json
      target: /usr/share/nginx/html/keycloak.json
      content: |
        {
          "realm": "{{central_keycloak_realm}}",
          "auth-server-url": "{{central_keycloak_base_url}}/auth/",
          "ssl-required": "external",
          "resource": "{{configurator_central_keycloak_resource}}",
          "public-client": true,
          "confidential-port": 0
        }
service:
  port: 80
kong:
  image: {{kong_configure_image}}
  tag: {{kong_configure_image_tag}}
  services:
    - name: configurator-ui
      authn: none
      response_transformers:
        - 'Cache-Control: no-cache'
        - 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload'
        - 'X-Content-Type-Options: nosniff'
        - 'X-XSS-Protection: 1; mode=block'
        - 'X-Frame-Options: SAMEORIGIN'
        - 'Permissions-Policy: geolocation=(); camera=(); microphone=()'
        - 'Referrer-Policy: no-referrer'
      remove_headers:
        - 'Server'
      service_path: /
      routes:
        hosts:
          - configurator.{{ep_base_domain}}
        preserve_host: "true"
