buildInfo:
  github_repo_name: {{github_repo_name}}
  ecr_repo_name: {{ecr_repo_name}}
app:
  image: {{app_image}}
  tag: {{app_image_tag}}
  port: 80
  monitoringPort: 80
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 10Mi
  limits:
    memory: 14Mi
env:
  secret:
    REACT_APP_GOOGLE_MAP_API_KEY: {{ GOOGLE_MAP_API_KEY }}
mounts:
  secret:
    - name: ep-app-data
      target: /var/www/EPAppData.js
      content: |
        window.epAppData = {
          API_BASE_URL: "https://api.{{esakha_base_domain}}",
          AUTH_ENDPOINT: "{{central_keycloak_base_url}}/auth",
          ENV_TYPE: "PROD",
          HOME_UI_BASE_URL: "https://home.{{esakha_base_domain}}",
          REACT_APP_GOOGLE_MAP_API_KEY: "{{ GOOGLE_MAP_API_KEY }}",
          SADHAN_API_BASE_URL: "https://api.{{sadhan_base_domain}}",
        }
    - name: keycloak-json
      target: /var/www/keycloak.json
      content: |
        {
          "realm": "{{central_keycloak_realm}}",
          "auth-server-url": "{{central_keycloak_base_url}}/auth/",
          "ssl-required": "external",
          "resource": "avantgarde-production-broadcast",
          "public-client": true,
          "confidential-port": 0
        }
service:
  port: 80
kong:
  image: {{kong_configure_image}}
  tag: {{kong_configure_image_tag}}
  services:
    - name: production-broadcast-ui
      authn: none
      cors_allowed_origins:
        - https://production-broadcast.{{esakha_base_domain}}
      response_transformers:
        - 'X-Frame-Options:SAMEORIGIN'
        - 'Permissions-Policy:geolocation=();camera=();microphone=()'
        - 'Cache-Control: no-cache'
        - 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload'
        - 'X-Content-Type-Options: nosniff'
        - 'X-XSS-Protection: 1; mode=block'
      service_path: /
      routes:
        hosts:
          - production-broadcast.{{esakha_base_domain}}
        preserve_host: "true"
