# Harry's Generated App Config: auth-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: harry-dev
  labels:
    app: auth-service
    environment: dev
    generated-by: harry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        environment: dev
    spec:
      containers:
      - name: auth-service
        image: java:openjdk-11
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  namespace: harry-dev
spec:
  selector:
    app: auth-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
