apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ include "app.namespace" . }}
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "app.name" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      {{- if .Values.hostAliases }}
      hostAliases:
      {{- range .Values.hostAliases }}
        - ip: {{ .ip }}
          hostnames:
            {{- toYaml .hostnames | nindent 10 }}
      {{- end }}
      {{- end }}
      volumes:
        {{- $appName := include "app.name" . -}}
          {{- include "volume.content" (dict "data" .Values.utils "appName" $appName) }}
      containers:
        {{- include "container.content" (dict "data" .Values.utils "appName" $appName) }}
